# Generated by Django 3.1.1 on 2021-09-01 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='customer',
            name='tid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='userid',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='userid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
